### ISSUE TITLE
Conflict - One or more of the specified volumes are not found or not in an available state..

### ISSUE THREAD

**Issue by josefredohd** [mosesman831/OCI-OcC-Fix#11]
[INFO] 2024-06-24 22:48:06,026 - 404 - NotAuthorizedOrNotFound - Available volume matching id ocid1.bootvolume.oc1.phx.abyhqljt7jo7gwi66yumrrpj5uahvt7speqinisxso7b7g4hsgk3us2gnkqq not found, or not authorized for the current user.. Retrying after 3 seconds. Number of Retry: 28

One question, if I don't have a boot volume compatible with VM.Standard.A1.Flex, will I not be able to use this script?  Please help me!!

**Comment by mosesman831** [comment]
I don't get your question, so you ran out of boot volume storage?
